Preserve lights' color & temperature (#75)
slashback100/presence_simulation pull request #76
Opened 2023-02-03 05:02 UTC by ValShaped

Modified update_entity to preserve color modes:
[color_temp, rgbww, rgbw, rgb, hs, xy]

2023-02-06 15:46 UTC, slashback100 approved these changes

2023-02-10 15:01 UTC, slashback100 requested changes

2023-02-10 15:01 UTC, slashback100 commented on custom_components/presence_simulation/__init__.py
> +                        service_data["color_temp"]  = state.attributes["color_temp"]
Something like this should work
```
            if "color_mode" in state.attributes:
                _LOGGER.debug("Got attribute color_mode: %s", state.attributes["color_mode"])
                color_mode = state.attributes["color_mode"]
                if color_mode != "color_temp":
                    #attribute color_mode will be hs, rgb...
                    color_mode = color_mode+"_color"
                if color_mode in state.attributes:
                    service_data[color_mode] = state.attributes[color_mode]
```

2023-02-11 00:23 UTC, ValShaped commented on custom_components/presence_simulation/__init__.py
> +                        service_data["color_temp"]  = state.attributes["color_temp"]
The Rust developer in me is cringing, and that'd break for lights that expose color modes not explicitly handled in my initial PR (i.e. "white" and "onoff" which have no associated color), but yeah, that could work for RGB/WW, HS, and XY lights. I'll try it out on my instance.

2023-02-11 04:00 UTC, ValShaped commented on custom_components/presence_simulation/__init__.py
> +                        service_data["color_temp"]  = state.attributes["color_temp"]
Fixed in https://github.com/slashback100/presence_simulation/pull/76/commits/96a274bcd56e6ee04ce339927da56c92a9e55865

2023-02-11 10:11 UTC, slashback100 approved these changes

2023-02-11 10:12 UTC, merged

2023-02-11 10:12 UTC, slashback100 commented
Thanks !